# Generated by Django 4.2.27 on 2025-12-03 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('role', models.CharField(choices=[('viewer', 'Пользователь'), ('editor', 'Редактор'), ('admin', 'Администратор')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(default=1)),
                ('uses', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ключ регистрации',
                'verbose_name_plural': 'Ключи регистрации',
            },
        ),
    ]
