# Generated by Django 4.2.27 on 2025-12-03 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registrationkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationkey',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
